### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by PajNath** [greglucas/pysecs#15]
Hi, 

I tried to make the code running by following the installation instruction, however, I haven't use python before and it seems that  the 2nd step is not working for me (pip did not work I guess is not installed). 

When I type 
$ python setup.py install 
it's doing a lot of stuffs of course but by the step 
byte-compiling  build/.../secs.py to secs.pyc 
there is an error  "SyntaxError : invalid syntax for the file secs.py line 147. The "@" seems to be the problem.
Then it continues to process and in the end the main error is "ImportError: no module named builtins". I googled it a bit but I'm not able to identify if the problem comes from the setup.py file itself or if I do not have a fully python environment working? 

Could you please help? I don't have enough knowledge to understand where is and how to solve the problem.
Thank you in advance for your answer.

**Comment by greglucas** [comment]
@PajNath, what version of Python are you using? This package requires Python > 3.6 which includes the `@` operator (introduced in 3.5). I can try to make this pip installable and put a release on PyPI in the next few days too, but it will still only include support for more recent Python versions.

**Comment by PajNath** [comment]
I actually have the 2 versions Python 2.7.17 (the one I was trying) and then 3.6.9 but then if I do 
$ python3 setup.py install
I don't get the error for the "@" indeed, but I get a "RuntimeError: Python version >= 3.7 required".

**Comment by greglucas** [comment]
Hm... It should work with 3.6, as we are testing on that version. Did you install numpy too, and if so, which version?

There is a Python3 wheel on PyPI, so can you try to install from that?
`pip3 install pysecs`

**Comment by PajNath** [comment]
$ pip3 install pysecs
worked ! :) but the pytest (and I tried python3 pytest) doesn't work? 
So it says that numpy-1.19.5 pysecs-0.1.1 has been installed

**Comment by greglucas** [comment]
Running the tests is another topic entirely and is installation dependent because it needs to know where source files are.

If you've got a working installation, I would ignore the testing suite for now if you're new to Python and use the examples to build off of.

**Comment by PajNath** [comment]
Ah ok, thanks a lot for your help!

**Comment by greglucas** [comment]
No problem, glad you got it installed and working! Feel free to open a new issue if you run into any other problems.
